# APD - Tema 1
# Octombrie 2021

build:
	@echo "Building..."
	@mpic++ tema3.cpp -o tema3
	@echo "Done"

build_debug:
	@echo "Building debug..."
	@mpic++ tema3.cpp -o tema3
	@echo "Done"

clean:
	@echo "Cleaning..."
	@rm -rf tema3
	@echo "Done"
